// automatically generated by write_DP_loops.pl

#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE5
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == VITERBI

#define WANT_COMP2_BEST
#define WANT_COMP5_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE5
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == VIT_BACK

#define WANT_COMP2_BEST
#define WANT_COMP5_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE5
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == FORWARD

#define WANT_COMP2_SUM
#define WANT_COMP5_SUM

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE5
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == BACKWARD

#define WANT_COMP2_SUM
#define WANT_COMP5_SUM

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE5
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == OPT_ACCUR

#define WANT_COMP2_BEST
#define WANT_COMP2_SUM
#define WANT_COMP5_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE5
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == VITERBI

#define WANT_COMP2_BEST
#define WANT_COMP4_BEST
#define WANT_COMP5_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE5
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == VIT_BACK

#define WANT_COMP3_BEST
#define WANT_COMP5_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE5
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == FORWARD

#define WANT_COMP2_SUM
#define WANT_COMP4_SUM
#define WANT_COMP5_SUM

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE5
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == BACKWARD

#define WANT_COMP2_SUM
#define WANT_COMP3_SUM
#define WANT_COMP5_SUM

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE5
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == OPT_ACCUR

#define WANT_COMP2_BEST
#define WANT_COMP2_SUM
#define WANT_COMP4_BEST
#define WANT_COMP5_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE6
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == VITERBI

#define WANT_COMP2_BEST
#define WANT_COMP6_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE6
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == VIT_BACK

#define WANT_COMP2_BEST
#define WANT_COMP6_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE6
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == FORWARD

#define WANT_COMP2_SUM
#define WANT_COMP6_SUM

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE6
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == BACKWARD

#define WANT_COMP2_SUM
#define WANT_COMP6_SUM

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE6
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == OPT_ACCUR

#define WANT_COMP2_BEST
#define WANT_COMP2_SUM
#define WANT_COMP6_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE6
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == VITERBI

#define WANT_COMP2_BEST
#define WANT_COMP4_BEST
#define WANT_COMP6_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE6
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == VIT_BACK

#define WANT_COMP2_BEST
#define WANT_COMP3_BEST
#define WANT_COMP4_BEST
#define WANT_COMP6_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE6
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == FORWARD

#define WANT_COMP2_SUM
#define WANT_COMP4_SUM
#define WANT_COMP6_SUM

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE6
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == BACKWARD

#define WANT_COMP2_SUM
#define WANT_COMP3_SUM
#define WANT_COMP4_SUM
#define WANT_COMP6_SUM

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE6
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == OPT_ACCUR

#define WANT_COMP2_BEST
#define WANT_COMP2_SUM
#define WANT_COMP4_BEST
#define WANT_COMP6_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE8
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == VITERBI

#define WANT_COMP1_BEST
#define WANT_COMP2_BEST
#define WANT_COMP8_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE8
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == VIT_BACK

#define WANT_COMP2_BEST
#define WANT_COMP6_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE8
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == FORWARD

#define WANT_COMP1_SUM
#define WANT_COMP2_SUM
#define WANT_COMP8_SUM

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE8
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == BACKWARD

#define WANT_COMP2_SUM
#define WANT_COMP6_SUM

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE8
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == OPT_ACCUR

#define WANT_COMP1_BEST
#define WANT_COMP2_BEST
#define WANT_COMP2_SUM
#define WANT_COMP8_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE8
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == VITERBI

#define WANT_COMP2_BEST
#define WANT_COMP4_BEST
#define WANT_COMP5_BEST
#define WANT_COMP8_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE8
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == VIT_BACK

#define WANT_COMP2_BEST
#define WANT_COMP3_BEST
#define WANT_COMP4_BEST
#define WANT_COMP6_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE8
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == FORWARD

#define WANT_COMP2_SUM
#define WANT_COMP4_SUM
#define WANT_COMP5_SUM
#define WANT_COMP8_SUM

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE8
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == BACKWARD

#define WANT_COMP2_SUM
#define WANT_COMP3_SUM
#define WANT_COMP4_SUM
#define WANT_COMP6_SUM

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE8
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == OPT_ACCUR

#define WANT_COMP2_BEST
#define WANT_COMP2_SUM
#define WANT_COMP4_BEST
#define WANT_COMP5_BEST
#define WANT_COMP8_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE9
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == VITERBI

#define WANT_COMP1_BEST
#define WANT_COMP2_BEST
#define WANT_COMP9_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE9
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == VIT_BACK

#define WANT_COMP1_BEST
#define WANT_COMP2_BEST
#define WANT_COMP7_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE9
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == FORWARD

#define WANT_COMP1_SUM
#define WANT_COMP2_SUM
#define WANT_COMP9_SUM

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE9
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == BACKWARD

#define WANT_COMP1_SUM
#define WANT_COMP2_SUM
#define WANT_COMP7_SUM

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE9
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == OPT_ACCUR

#define WANT_COMP1_BEST
#define WANT_COMP2_BEST
#define WANT_COMP2_SUM
#define WANT_COMP8_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE9
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == VITERBI

#define WANT_COMP2_BEST
#define WANT_COMP3_BEST
#define WANT_COMP4_BEST
#define WANT_COMP6_BEST
#define WANT_COMP9_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE9
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == VIT_BACK

#define WANT_COMP2_BEST
#define WANT_COMP3_BEST
#define WANT_COMP4_BEST
#define WANT_COMP5_BEST
#define WANT_COMP7_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE9
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == FORWARD

#define WANT_COMP2_SUM
#define WANT_COMP3_SUM
#define WANT_COMP4_SUM
#define WANT_COMP6_SUM
#define WANT_COMP9_SUM

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE9
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == BACKWARD

#define WANT_COMP2_SUM
#define WANT_COMP3_SUM
#define WANT_COMP4_SUM
#define WANT_COMP5_SUM
#define WANT_COMP7_SUM

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN7
#if PAIR_HMM_STATES == SPACE9
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == OPT_ACCUR

#define WANT_COMP2_BEST
#define WANT_COMP2_SUM
#define WANT_COMP4_BEST
#define WANT_COMP5_BEST
#define WANT_COMP8_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE5
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == VITERBI

#define WANT_COMP2_BEST
#define WANT_COMP5_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE5
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == VIT_BACK

#define WANT_COMP2_BEST
#define WANT_COMP5_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE5
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == FORWARD

#define WANT_COMP2_SUM
#define WANT_COMP5_SUM

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE5
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == BACKWARD

#define WANT_COMP2_SUM
#define WANT_COMP5_SUM

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE5
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == OPT_ACCUR

#define WANT_COMP2_BEST
#define WANT_COMP2_SUM
#define WANT_COMP5_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE5
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == VITERBI

#define WANT_COMP3_BEST
#define WANT_COMP5_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE5
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == VIT_BACK

#define WANT_COMP4_BEST
#define WANT_COMP5_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE5
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == FORWARD

#define WANT_COMP2_SUM
#define WANT_COMP3_SUM
#define WANT_COMP5_SUM

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE5
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == BACKWARD

#define WANT_COMP2_SUM
#define WANT_COMP4_SUM
#define WANT_COMP5_SUM

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE5
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == OPT_ACCUR

#define WANT_COMP2_SUM
#define WANT_COMP3_BEST
#define WANT_COMP5_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE6
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == VITERBI

#define WANT_COMP2_BEST
#define WANT_COMP6_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE6
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == VIT_BACK

#define WANT_COMP2_BEST
#define WANT_COMP6_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE6
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == FORWARD

#define WANT_COMP2_SUM
#define WANT_COMP6_SUM

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE6
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == BACKWARD

#define WANT_COMP2_SUM
#define WANT_COMP6_SUM

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE6
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == OPT_ACCUR

#define WANT_COMP2_BEST
#define WANT_COMP2_SUM
#define WANT_COMP6_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE6
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == VITERBI

#define WANT_COMP3_BEST
#define WANT_COMP6_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE6
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == VIT_BACK

#define WANT_COMP4_BEST
#define WANT_COMP5_BEST
#define WANT_COMP6_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE6
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == FORWARD

#define WANT_COMP2_SUM
#define WANT_COMP3_SUM
#define WANT_COMP6_SUM

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE6
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == BACKWARD

#define WANT_COMP2_SUM
#define WANT_COMP4_SUM
#define WANT_COMP5_SUM
#define WANT_COMP6_SUM

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE6
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == OPT_ACCUR

#define WANT_COMP2_SUM
#define WANT_COMP3_BEST
#define WANT_COMP6_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE8
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == VITERBI

#define WANT_COMP1_BEST
#define WANT_COMP2_BEST
#define WANT_COMP8_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE8
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == VIT_BACK

#define WANT_COMP2_BEST
#define WANT_COMP6_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE8
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == FORWARD

#define WANT_COMP1_SUM
#define WANT_COMP2_SUM
#define WANT_COMP8_SUM

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE8
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == BACKWARD

#define WANT_COMP2_SUM
#define WANT_COMP6_SUM

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE8
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == OPT_ACCUR

#define WANT_COMP1_BEST
#define WANT_COMP2_BEST
#define WANT_COMP2_SUM
#define WANT_COMP8_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE8
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == VITERBI

#define WANT_COMP2_BEST
#define WANT_COMP3_BEST
#define WANT_COMP8_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE8
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == VIT_BACK

#define WANT_COMP4_BEST
#define WANT_COMP5_BEST
#define WANT_COMP6_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE8
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == FORWARD

#define WANT_COMP2_SUM
#define WANT_COMP3_SUM
#define WANT_COMP8_SUM

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE8
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == BACKWARD

#define WANT_COMP2_SUM
#define WANT_COMP4_SUM
#define WANT_COMP5_SUM
#define WANT_COMP6_SUM

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE8
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == OPT_ACCUR

#define WANT_COMP2_BEST
#define WANT_COMP2_SUM
#define WANT_COMP3_BEST
#define WANT_COMP8_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE9
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == VITERBI

#define WANT_COMP1_BEST
#define WANT_COMP2_BEST
#define WANT_COMP9_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE9
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == VIT_BACK

#define WANT_COMP1_BEST
#define WANT_COMP2_BEST
#define WANT_COMP7_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE9
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == FORWARD

#define WANT_COMP1_SUM
#define WANT_COMP2_SUM
#define WANT_COMP9_SUM

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE9
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == BACKWARD

#define WANT_COMP1_SUM
#define WANT_COMP2_SUM
#define WANT_COMP7_SUM

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE9
#if PAIR_HMM_TRANS  == VIA_MM
#if ALGORITHM       == OPT_ACCUR

#define WANT_COMP1_BEST
#define WANT_COMP2_BEST
#define WANT_COMP2_SUM
#define WANT_COMP8_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE9
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == VITERBI

#define WANT_COMP3_BEST
#define WANT_COMP8_BEST
#define WANT_COMP9_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE9
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == VIT_BACK

#define WANT_COMP5_BEST
#define WANT_COMP6_BEST
#define WANT_COMP7_BEST

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE9
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == FORWARD

#define WANT_COMP2_SUM
#define WANT_COMP3_SUM
#define WANT_COMP8_SUM
#define WANT_COMP9_SUM

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE9
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == BACKWARD

#define WANT_COMP2_SUM
#define WANT_COMP5_SUM
#define WANT_COMP6_SUM
#define WANT_COMP7_SUM

#endif
#endif
#endif
#endif


#if PROF_HMM_TRANS  == PLAN9
#if PAIR_HMM_STATES == SPACE9
#if PAIR_HMM_TRANS  == ALL_TRANS
#if ALGORITHM       == OPT_ACCUR

#define WANT_COMP2_BEST
#define WANT_COMP2_SUM
#define WANT_COMP3_BEST
#define WANT_COMP8_BEST

#endif
#endif
#endif
#endif


