// automatically generated by write_DP_loops.pl

#if ALGO_SPACE==LINSPACE

#ifdef WANT_COMP1_SUM
#error "VIA_MM will not work with SPACE8 or SPACE9!"
#endif

#ifdef WANT_COMP2_SUM
#define comp2_sum comp2_sum_lin
static double comp2_sum_lin ( double sc1, double sc2 )
{
	return sc1+sc2;
}
#endif

#ifdef WANT_COMP3_SUM
#define comp3_sum comp3_sum_lin
static double comp3_sum_lin ( double sc1, double sc2, double sc3 )
{
	return sc1+sc2+sc3;
}
#endif

#ifdef WANT_COMP4_SUM
#define comp4_sum comp4_sum_lin
static double comp4_sum_lin ( double sc1, double sc2, double sc3, double sc4 )
{
	return sc1+sc2+sc3+sc4;
}
#endif

#ifdef WANT_COMP5_SUM
#define comp5_sum comp5_sum_lin
static double comp5_sum_lin ( double sc1, double sc2, double sc3, double sc4, double sc5 )
{
	return sc1+sc2+sc3+sc4+sc5;
}
#endif

#ifdef WANT_COMP6_SUM
#define comp6_sum comp6_sum_lin
static double comp6_sum_lin ( double sc1, double sc2, double sc3, double sc4, double sc5, double sc6 )
{
	return sc1+sc2+sc3+sc4+sc5+sc6;
}
#endif

#ifdef WANT_COMP7_SUM
#define comp7_sum comp7_sum_lin
static double comp7_sum_lin ( double sc1, double sc2, double sc3, double sc4, double sc5, double sc6, double sc7 )
{
	return sc1+sc2+sc3+sc4+sc5+sc6+sc7;
}
#endif

#ifdef WANT_COMP8_SUM
#define comp8_sum comp8_sum_lin
static double comp8_sum_lin ( double sc1, double sc2, double sc3, double sc4, double sc5, double sc6, double sc7, double sc8 )
{
	return sc1+sc2+sc3+sc4+sc5+sc6+sc7+sc8;
}
#endif

#ifdef WANT_COMP9_SUM
#define comp9_sum comp9_sum_lin
static double comp9_sum_lin ( double sc1, double sc2, double sc3, double sc4, double sc5, double sc6, double sc7, double sc8, double sc9 )
{
	return sc1+sc2+sc3+sc4+sc5+sc6+sc7+sc8+sc9;
}
#endif

#endif


#if ALGO_SPACE==LOGSPACE

#ifdef WANT_COMP1_SUM
#error "VIA_MM will not work with SPACE8 or SPACE9!"
#endif

#ifdef WANT_COMP2_SUM
#define comp2_sum comp2_sum_log
static double comp2_sum_log ( double sc1, double sc2 )
{
	double sc;
	
	if( sc1 < sc2 ) sc = sc2 + log(1.0 + exp(sc1-sc2));
	else            sc = sc1 + log(1.0 + exp(sc2-sc1));
	
	return sc;
}
#endif

#ifdef WANT_COMP3_SUM
#define comp3_sum comp3_sum_log
static double comp3_sum_log ( double sc1, double sc2, double sc3 )
{
	double max = sc1;
	
	if( max < sc2 ) max = sc2;
	if( max < sc3 ) max = sc3;
	
	return max+log(exp(sc1-max)+exp(sc2-max)+exp(sc3-max));
}
#endif

#ifdef WANT_COMP4_SUM
#define comp4_sum comp4_sum_log
static double comp4_sum_log ( double sc1, double sc2, double sc3, double sc4 )
{
	double max = sc1;
	
	if( max < sc2 ) max = sc2;
	if( max < sc3 ) max = sc3;
	if( max < sc4 ) max = sc4;
	
	return max+log(exp(sc1-max)+exp(sc2-max)+exp(sc3-max)+exp(sc4-max));
}
#endif

#ifdef WANT_COMP5_SUM
#define comp5_sum comp5_sum_log
static double comp5_sum_log ( double sc1, double sc2, double sc3, double sc4, double sc5 )
{
	double max = sc1;
	
	if( max < sc2 ) max = sc2;
	if( max < sc3 ) max = sc3;
	if( max < sc4 ) max = sc4;
	if( max < sc5 ) max = sc5;
	
	return max+log(exp(sc1-max)+exp(sc2-max)+exp(sc3-max)+exp(sc4-max)+exp(sc5-max));
}
#endif

#ifdef WANT_COMP6_SUM
#define comp6_sum comp6_sum_log
static double comp6_sum_log ( double sc1, double sc2, double sc3, double sc4, double sc5, double sc6 )
{
	double max = sc1;
	
	if( max < sc2 ) max = sc2;
	if( max < sc3 ) max = sc3;
	if( max < sc4 ) max = sc4;
	if( max < sc5 ) max = sc5;
	if( max < sc6 ) max = sc6;
	
	return max+log(exp(sc1-max)+exp(sc2-max)+exp(sc3-max)+exp(sc4-max)+exp(sc5-max)+exp(sc6-max));
}
#endif

#ifdef WANT_COMP7_SUM
#define comp7_sum comp7_sum_log
static double comp7_sum_log ( double sc1, double sc2, double sc3, double sc4, double sc5, double sc6, double sc7 )
{
	double max = sc1;
	
	if( max < sc2 ) max = sc2;
	if( max < sc3 ) max = sc3;
	if( max < sc4 ) max = sc4;
	if( max < sc5 ) max = sc5;
	if( max < sc6 ) max = sc6;
	if( max < sc7 ) max = sc7;
	
	return max+log(exp(sc1-max)+exp(sc2-max)+exp(sc3-max)+exp(sc4-max)+exp(sc5-max)+exp(sc6-max)+exp(sc7-max));
}
#endif

#ifdef WANT_COMP8_SUM
#define comp8_sum comp8_sum_log
static double comp8_sum_log ( double sc1, double sc2, double sc3, double sc4, double sc5, double sc6, double sc7, double sc8 )
{
	double max = sc1;
	
	if( max < sc2 ) max = sc2;
	if( max < sc3 ) max = sc3;
	if( max < sc4 ) max = sc4;
	if( max < sc5 ) max = sc5;
	if( max < sc6 ) max = sc6;
	if( max < sc7 ) max = sc7;
	if( max < sc8 ) max = sc8;
	
	return max+log(exp(sc1-max)+exp(sc2-max)+exp(sc3-max)+exp(sc4-max)+exp(sc5-max)+exp(sc6-max)+exp(sc7-max)+exp(sc8-max));
}
#endif

#ifdef WANT_COMP9_SUM
#define comp9_sum comp9_sum_log
static double comp9_sum_log ( double sc1, double sc2, double sc3, double sc4, double sc5, double sc6, double sc7, double sc8, double sc9 )
{
	double max = sc1;
	
	if( max < sc2 ) max = sc2;
	if( max < sc3 ) max = sc3;
	if( max < sc4 ) max = sc4;
	if( max < sc5 ) max = sc5;
	if( max < sc6 ) max = sc6;
	if( max < sc7 ) max = sc7;
	if( max < sc8 ) max = sc8;
	if( max < sc9 ) max = sc9;
	
	return max+log(exp(sc1-max)+exp(sc2-max)+exp(sc3-max)+exp(sc4-max)+exp(sc5-max)+exp(sc6-max)+exp(sc7-max)+exp(sc8-max)+exp(sc9-max));
}
#endif

#endif


#ifdef WANT_COMP1_BEST
#error "VIA_MM will not work with SPACE8 or SPACE9!"
#endif
#ifdef WANT_COMP2_BEST
static double comp2_best ( int *tr, int st1, double sc1, int st2, double sc2 )
{
	double sc = sc1;
	int   st = st1;
	
	if( sc2 > sc ){ sc = sc2; st = st2; };
	
	*tr = st;
	return sc;
}
#endif

#ifdef WANT_COMP3_BEST
static double comp3_best ( int *tr, int st1, double sc1, int st2, double sc2, int st3, double sc3 )
{
	double sc = sc1;
	int   st = st1;
	
	if( sc2 > sc ){ sc = sc2; st = st2; };
	if( sc3 > sc ){ sc = sc3; st = st3; };
	
	*tr = st;
	return sc;
}
#endif

#ifdef WANT_COMP4_BEST
static double comp4_best ( int *tr, int st1, double sc1, int st2, double sc2, int st3, double sc3, int st4, double sc4 )
{
	double sc = sc1;
	int   st = st1;
	
	if( sc2 > sc ){ sc = sc2; st = st2; };
	if( sc3 > sc ){ sc = sc3; st = st3; };
	if( sc4 > sc ){ sc = sc4; st = st4; };
	
	*tr = st;
	return sc;
}
#endif

#ifdef WANT_COMP5_BEST
static double comp5_best ( int *tr, int st1, double sc1, int st2, double sc2, int st3, double sc3, int st4, double sc4, int st5, double sc5 )
{
	double sc = sc1;
	int   st = st1;
	
	if( sc2 > sc ){ sc = sc2; st = st2; };
	if( sc3 > sc ){ sc = sc3; st = st3; };
	if( sc4 > sc ){ sc = sc4; st = st4; };
	if( sc5 > sc ){ sc = sc5; st = st5; };
	
	*tr = st;
	return sc;
}
#endif

#ifdef WANT_COMP6_BEST
static double comp6_best ( int *tr, int st1, double sc1, int st2, double sc2, int st3, double sc3, int st4, double sc4, int st5, double sc5, int st6, double sc6 )
{
	double sc = sc1;
	int   st = st1;
	
	if( sc2 > sc ){ sc = sc2; st = st2; };
	if( sc3 > sc ){ sc = sc3; st = st3; };
	if( sc4 > sc ){ sc = sc4; st = st4; };
	if( sc5 > sc ){ sc = sc5; st = st5; };
	if( sc6 > sc ){ sc = sc6; st = st6; };
	
	*tr = st;
	return sc;
}
#endif

#ifdef WANT_COMP7_BEST
static double comp7_best ( int *tr, int st1, double sc1, int st2, double sc2, int st3, double sc3, int st4, double sc4, int st5, double sc5, int st6, double sc6, int st7, double sc7 )
{
	double sc = sc1;
	int   st = st1;
	
	if( sc2 > sc ){ sc = sc2; st = st2; };
	if( sc3 > sc ){ sc = sc3; st = st3; };
	if( sc4 > sc ){ sc = sc4; st = st4; };
	if( sc5 > sc ){ sc = sc5; st = st5; };
	if( sc6 > sc ){ sc = sc6; st = st6; };
	if( sc7 > sc ){ sc = sc7; st = st7; };
	
	*tr = st;
	return sc;
}
#endif

#ifdef WANT_COMP8_BEST
static double comp8_best ( int *tr, int st1, double sc1, int st2, double sc2, int st3, double sc3, int st4, double sc4, int st5, double sc5, int st6, double sc6, int st7, double sc7, int st8, double sc8 )
{
	double sc = sc1;
	int   st = st1;
	
	if( sc2 > sc ){ sc = sc2; st = st2; };
	if( sc3 > sc ){ sc = sc3; st = st3; };
	if( sc4 > sc ){ sc = sc4; st = st4; };
	if( sc5 > sc ){ sc = sc5; st = st5; };
	if( sc6 > sc ){ sc = sc6; st = st6; };
	if( sc7 > sc ){ sc = sc7; st = st7; };
	if( sc8 > sc ){ sc = sc8; st = st8; };
	
	*tr = st;
	return sc;
}
#endif

#ifdef WANT_COMP9_BEST
static double comp9_best ( int *tr, int st1, double sc1, int st2, double sc2, int st3, double sc3, int st4, double sc4, int st5, double sc5, int st6, double sc6, int st7, double sc7, int st8, double sc8, int st9, double sc9 )
{
	double sc = sc1;
	int   st = st1;
	
	if( sc2 > sc ){ sc = sc2; st = st2; };
	if( sc3 > sc ){ sc = sc3; st = st3; };
	if( sc4 > sc ){ sc = sc4; st = st4; };
	if( sc5 > sc ){ sc = sc5; st = st5; };
	if( sc6 > sc ){ sc = sc6; st = st6; };
	if( sc7 > sc ){ sc = sc7; st = st7; };
	if( sc8 > sc ){ sc = sc8; st = st8; };
	if( sc9 > sc ){ sc = sc9; st = st9; };
	
	*tr = st;
	return sc;
}
#endif

